/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/avatar.glb");

  useFrame((state) => {
    state.camera.fov = 70;
    state.camera.updateProjectionMatrix();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AvatarRoot" userData={{ name: "AvatarRoot" }}>
          <group name="EyeLeft" userData={{ name: "EyeLeft" }}>
            <skinnedMesh
              name="mesh_0"
              geometry={nodes.mesh_0.geometry}
              material={materials.Wolf3D_Eye}
              skeleton={nodes.mesh_0.skeleton}
              position={[0, 0.4, -0.13]}
              scale={[0.0000236187552, 0.0000236187552, 0.0000236187552]}
            />
          </group>
          <group name="Wolf3D_Glasses" userData={{ name: "Wolf3D_Glasses" }}>
            <skinnedMesh
              name="mesh_1"
              geometry={nodes.mesh_1.geometry}
              material={materials.Wolf3D_Glasses}
              skeleton={nodes.mesh_1.skeleton}
              position={[-0.11, 0.4, -0.13]}
              scale={[0.0000236187552, 0.0000236187552, 0.0000236187552]}
            />
          </group>
          <group name="Wolf3D_Hair" userData={{ name: "Wolf3D_Hair" }}>
            <skinnedMesh
              name="mesh_2"
              geometry={nodes.mesh_2.geometry}
              material={materials.Wolf3D_Hair}
              skeleton={nodes.mesh_2.skeleton}
              position={[-0.11, 0.4, -0.13]}
              scale={[0.0000236187552, 0.0000236187552, 0.0000236187552]}
            />
          </group>
          <group name="Wolf3D_Head" userData={{ name: "Wolf3D_Head" }}>
            <skinnedMesh
              name="mesh_3"
              geometry={nodes.mesh_3.geometry}
              material={materials.Wolf3D_Skin}
              skeleton={nodes.mesh_3.skeleton}
              morphTargetDictionary={nodes.mesh_3.morphTargetDictionary}
              morphTargetInfluences={nodes.mesh_3.morphTargetInfluences}
              position={[-0.11, 0.4, -0.13]}
              scale={[0.0000236187552, 0.0000236187552, 0.0000236187552]}
              userData={{
                targetNames: ["mouthOpen", "smile", "blink", "eyebrows"],
              }}
            />
          </group>
          <group name="Wolf3D_Teeth" userData={{ name: "Wolf3D_Teeth" }}>
            <skinnedMesh
              name="mesh_5"
              geometry={nodes.mesh_5.geometry}
              material={materials.Wolf3D_Teeth}
              skeleton={nodes.mesh_5.skeleton}
              position={[-0.11, 0.4, -0.13]}
              scale={[0.0000236187552, 0.0000236187552, 0.0000236187552]}
            />
          </group>
          <primitive object={nodes.Hips} />
        </group>
        <mesh
          name="mesh_4"
          geometry={nodes.mesh_4.geometry}
          material={materials.Wolf3D_Shirt}
          position={[-0.11, 0.4, -0.13]}
          scale={[0.0000236187552, 0.0000236187552, 0.0000236187552]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/avatar.glb");
