/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zafflex (https://sketchfab.com/Zafflex)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-goat-e08bb2e734004870b1ed4c21f111a854
title: Low-poly Goat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/goat/output.glb");

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[1.46, 0, 0.54]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.51, 1.43, 1.43]}
        >
          <group
            position={[-9.97, 1.45, 0.35]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.18, 0.06, 0.06]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Icosphere_0.geometry}
              material={nodes.Icosphere_0.material}
            />
          </group>
          <group
            position={[-9.97, 1.45, -0.35]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.18, 0.06, 0.06]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Icosphere001_0.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_0.geometry}
            material={materials.Goat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_1.geometry}
            material={materials.Goat_Horn}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_3.geometry}
            material={nodes.Plane_3.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_2.geometry}
            material={materials.Goat_Claws}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/goat/output.glb");
